src/Entity/Shop.php
<?php

namespace App\Entity;

use App\Repository\ShopRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShopRepository::class)]
class Shop
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'shops')]
    private $user;

    #[ORM\Column(type: 'string')]
    private $order_status;

    #[ORM\Column(type: 'datetime')]
    private $order_date;

    #[ORM\Column(type: 'datetime')]
    private $shipping_date;

    #[ORM\Column(type: 'decimal', precision: 10, scale: 2)]
    private $price_order;

    #[ORM\OneToMany(mappedBy: 'shop', targetEntity: ShopBeer::class)]
    private $shopBeers;

    #[ORM\ManyToOne(targetEntity: User::class)]
    private $email_user;

    public function __construct()
    {
        $this->shopBeers = new ArrayCollection();
        $this->beer = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    // public function __toString(): string
    // {
    //     // TODO: Implement __toString() method.
    //     return $this->user;
    // }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getOrderStatus(): ?string
    {
        return $this->order_status;
    }

    public function setOrderStatus(string $order_status): self
    {
        $this->order_status = $order_status;

        return $this;
    }

    public function getOrderDate(): ?\DateTimeInterface
    {
        return $this->order_date;
    }

    public function setOrderDate(\DateTimeInterface $order_date): self
    {
        $this->order_date = $order_date;

        return $this;
    }

    public function getShippingDate(): ?\DateTimeInterface
    {
        return $this->shipping_date;
    }

    public function setShippingDate(\DateTimeInterface $shipping_date): self
    {
        $this->shipping_date = $shipping_date;

        return $this;
    }

    public function getPriceOrder(): ?string
    {
        return $this->price_order;
    }

    public function setPriceOrder(string $price_order): self
    {
        $this->price_order = $price_order;

        return $this;
    }

    /**
     * @return Collection<int, ShopBeer>
     */
    public function getShopBeers(): Collection
    {
        return $this->shopBeers;
    }

    public function addShopBeer(ShopBeer $shopBeer): self
    {
        if (!$this->shopBeers->contains($shopBeer)) {
            $this->shopBeers[] = $shopBeer;
            $shopBeer->setShop($this);
        }

        return $this;
    }

    public function removeShopBeer(ShopBeer $shopBeer): self
    {
        if ($this->shopBeers->removeElement($shopBeer)) {
            // set the owning side to null (unless already changed)
            if ($shopBeer->getShop() === $this) {
                $shopBeer->setShop(null);
            }
        }

        return $this;
    }

}

src/Entity/ShopBeer.php
<?php

namespace App\Entity;

use App\Repository\ShopBeerRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShopBeerRepository::class)]
class ShopBeer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer')]
    private $quantity;

    #[ORM\Column(type: 'decimal', precision: 10, scale: 2)]
    private $price_quantity;

    #[ORM\ManyToOne(targetEntity: Beer::class, inversedBy: 'shopBeers')]
    #[ORM\JoinColumn(nullable: false)]
    private $beer;

    #[ORM\ManyToOne(targetEntity: Shop::class, inversedBy: 'shopBeers')]
    private $shop;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPriceQuantity(): ?string
    {
        return $this->price_quantity;
    }

    public function setPriceQuantity(string $price_quantity): self
    {
        $this->price_quantity = $price_quantity;

        return $this;
    }

    public function getBeer(): ?Beer
    {
        return $this->beer;
    }

    public function setBeer(?Beer $beer): self
    {
        $this->beer = $beer;

        return $this;
    }

    public function getShop(): ?Shop
    {
        return $this->shop;
    }

    public function setShop(?Shop $shop): self
    {
        $this->shop = $shop;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $last_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $first_name;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $pseudo;

    #[ORM\Column(type: 'string', length: 255)]
    private $adress;

    #[ORM\Column(type: 'string', length: 255)]
    private $city;

    #[ORM\Column(type: 'integer')]
    private $postal_code;

    #[ORM\Column(type: 'bigint')]
    private $phone;

    #[ORM\Column(type: 'datetime')]
    private $birthday_date;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Shop::class)]
    private $shops;

    #[ORM\ManyToMany(targetEntity: Beer::class, inversedBy: 'users')]
    private $favoris;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Notice::class)]
    private $notices;

    public function __construct()
    {
        $this->shops = new ArrayCollection();
        $this->favoris = new ArrayCollection();
        $this->notices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(int $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getBirthdayDate(): ?\DateTimeInterface
    {
        return $this->birthday_date;
    }

    public function setBirthdayDate(\DateTimeInterface $birthday_date): self
    {
        $this->birthday_date = $birthday_date;

        return $this;
    }

    /**
     * @return Collection<int, Shop>
     */
    public function getShops(): Collection
    {
        return $this->shops;
    }

    public function addShop(Shop $shop): self
    {
        if (!$this->shops->contains($shop)) {
            $this->shops[] = $shop;
            $shop->setUser($this);
        }

        return $this;
    }

    public function removeShop(Shop $shop): self
    {
        if ($this->shops->removeElement($shop)) {
            // set the owning side to null (unless already changed)
            if ($shop->getUser() === $this) {
                $shop->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Beer>
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(Beer $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris[] = $favori;
        }

        return $this;
    }

    public function removeFavori(Beer $favori): self
    {
        $this->favoris->removeElement($favori);

        return $this;
    }

    /**
     * @return Collection<int, Notice>
     */
    public function getNotices(): Collection
    {
        return $this->notices;
    }

    public function addNotice(Notice $notice): self
    {
        if (!$this->notices->contains($notice)) {
            $this->notices[] = $notice;
            $notice->setUser($this);
        }

        return $this;
    }

    public function removeNotice(Notice $notice): self
    {
        if ($this->notices->removeElement($notice)) {
            // set the owning side to null (unless already changed)
            if ($notice->getUser() === $this) {
                $notice->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\BeerRepository;
use App\Repository\ShopRepository;
use App\Repository\UserRepository;
use App\Repository\ShopBeerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface as Hasher;

class ProfilController extends AbstractController
{
    #[Route('/profil', name: 'app_profil')]
    public function index(ShopRepository $sr): Response
    {
        return $this->render('profil/index.html.twig');
    }

    #[Route('/orders/{id}', name: 'app_profil_orders', methods: ['GET', 'POST'])]
    public function orders(ShopRepository $sr, User $user, $id) : Response
    {
        $shops = $sr->findByUser($id);
        return $this->render('profil/orders.html.twig', [
            'shops' => $shops,
        ]);
    }

    #[Route('/edituser/{id}', name: 'app_profil_edituser', methods: ['GET', 'POST'], requirements: ['id' => '[0-9]+'])]
    public function editUser(ShopRepository $sr,  User $user, UserRepository $userRepository, Hasher $hasher, Request $request, EntityManagerInterface $em) : Response
    {
        $formuser = $this->createForm(UserType::class, $user);
        $formuser->handleRequest($request);
        if ($formuser->isSubmitted() && $formuser->isValid()) {
                
            if( $mdp = $formuser->get('plainPassword')->getData()){
                $password = $hasher->hashPassword($user, $mdp);
                $user->setPassword($password);}
    
            $em->flush();
            echo "<pre>";
                print_r($user->getPassword());
            echo "</pre>";
            return $this->redirectToRoute('app_profil', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('profil/edit.html.twig', [
            'formuser' => $formuser,
        ]);
    }

    #[Route('/details/{id}', name: 'app_details_order', methods: ['GET', 'POST'], requirements: ['id' => '[0-9]+'])]
    public function details(ShopRepository $sr, ShopBeerRepository $sbr,  UserRepository $userRepository, Request $request, $id, BeerRepository $br) : Response
    {
        $com = $request->query->get('com');
        $shops = $sr->findByUser($id);
        return $this->renderForm('profil/details.html.twig', [
           'id' => $id,
           'com' => $com,
           "beers" => $br->findAll(),
           "shopbeer" => $sbr->findAll(),
           'shops' => $shops
        ]);
    }
}

templates/profil/details.html.twig
{% extends 'base.html.twig' %}

{% block body2 %}
    <div class="container">
        <div id="profilPresent">
            <h2>Détails commande n°{{com}}</h2>
            {% if app.user %}
            <a href="{{ path('app_profil_orders', {'id': id}) }}">
                <button class="sbutton3">Retour commande</button>
            </a>
            {% if shops is defined %}
            {% for shop in shops %}
            <div class="col-0 flex">
            {% if beers is defined %}
            {% for beer in beers %}
                {% for shopbe in shopbeer %}
                    {% if shopbe.shop.id == com %}
                        {% if shop.id == com %}
                            {% if beer.id == shopbe.beer.id %}
                            <div id="beer{{ beer.id }}" class="flex blocSP col-2">
                                <div class="col-4 text-center">
                                    <img src="{{ asset('img/' ~ beer.photo) }}" alt="">
                                </div>
                                <div class="sPresent col-70">
                                    <div class="text-left">
                                        <h4>{{ beer.name }}</h4>
                                        <h5>{{ beer.category.name }}</h5>
                                    </div>
                                    <div class="col-60">
                                        <div>
                                            <p><span>Prix unitaire:</span> {{ beer.price[2:] == '.00' ? beer.price[:1] : beer.price }}€</p>
                                            <p><span>Quantité achetée:</span> {{ shopbe.quantity }}</p>
                                            <p><span>Prix total:</span> {{ shopbe.priceQuantity }}€</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% endfor %}
            {% endfor %}
            {% endif %}
            </div>
            <div class="col-0 flex help-text">
            {% if shop.id == com %}
                <p class="col-2"><span>Statut de la commande:</span>{% if shop.orderStatus == 0 %}en cours de préparation{% elseif shop.orderStatus == 1 %}en préparation{% elseif shop.orderStatus == 2 %}en cours d'acheminement{% elseif shop.orderStatus == 3 %}livrée{% endif %}</p>    
                <p class="col-2"><span>Date de la commande :</span>{{ shop.orderDate|date('d/m/Y') }}</p>    
                <p class="col-2" style="order: 4"><span>Date de livraison prévue :</span>{{ shop.shippingDate|date('d/m/Y') }}</p>    
                <p class="col-2"><span>Montant total de la commande :</span>{{ shop.priceOrder }}€</p>
            {% endif %} 
            </div>
            {% endfor %}
            {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/profil/edit.html.twig
{% extends 'base.html.twig' %}

{% block body2 %}
    <div class="container">
        <div id="profilPresent">
            <h2>Modifier profil</h2>
            <a href="{{ path('app_profil') }}">
                <button class="sbutton3">Retour profil</button>
            </a>
            {% if app.user %}
                <div  class="text-center">
                    {{ form_start(formuser) }}
                        {{ form_row(formuser.email) }}
                        {{ form_row(formuser.plainPassword, {
                            label: 'Mot de passe'
                        }) }}
                        {{ form_row(formuser.last_name) }}
                        {{ form_row(formuser.first_name) }}
                        {{ form_row(formuser.pseudo) }}
                        {{ form_row(formuser.adress) }}
                        {{ form_row(formuser.city) }}
                        {{ form_row(formuser.postalCode) }}
                        {{ form_row(formuser.phone) }}
                        {{ form_row(formuser.birthday_date) }}
                        <input type="submit" class="submit" value="Valider">
                    {{ form_end(formuser) }}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block body2 %}
    <div class="container">
        <div id="profilPresent">
            <h2>Profil</h2>
            {% if app.user %}
                <div>
                    <h3>Mes informations</h3>
                    <a href="{{ path('app_logout') }}">
                        <button class="sbutton3">Déconnexion</button>
                    </a>
                    <a href="{{ path('app_profil_orders', {'id' : app.user.id }) }}">
                        <button class="sbutton1">Voir mes commandes</button>
                    </a>
                    <a href="{{ path('app_profil_edituser', {'id' : app.user.id }) }}">
                        <button class="sbutton2">Modifier mes informations</button>
                    </a>
                    <div>
                        <p><span>Pseudo :</span>{{ app.user.pseudo }}</p>
                        <p><span>Nom :</span>{{ app.user.lastName }}</p>
                        <p><span>Prénom :</span>{{ app.user.firstName }}</p>
                        <p><span>E-mail :</span>{{ app.user.email }}</p>
                        <p><span>Mot de passe :</span>********</p>
                        <p><span>Adresse</span>{{ app.user.adress }}</p>
                        <p><span>Ville</span>{{ app.user.city }}</p>
                        <p><span>Code Postal</span>{{ app.user.postalCode }}</p>
                        <p><span>Téléphone</span>{{ app.user.phone }}</p>
                        <p><span>Date d'anniversaire</span>{{ app.user.birthdayDate|date('d/m/Y') }}</p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/profil/orders.html.twig
{% extends 'base.html.twig' %}

{% block body2 %}
    <div class="container">
        <div id="profilPresent">
            <h2>Mes commandes</h2>
            <a href="{{ path('app_profil') }}">
                <button class="sbutton3">Retour profil</button>
            </a>
            <div class="flex col-0">
                {% for shop in shops %}
                    <div class="blocSP col-3">
                        <p><span>Commande n°:</span>{{ shop.id }}</p>
                        <a href="{{ path('app_details_order', {'id' : app.user.id, 'com': shop.id }) }}">
                            <button class="sbutton4">Détail commande</button>
                        </a>
                        <p><span>Statut :</span>{% if shop.orderStatus == 0 %}en cours de préparation{% elseif shop.orderStatus == 1 %}en préparation{% elseif shop.orderStatus == 2 %}en cours d'acheminement{% elseif shop.orderStatus == 3 %}livrée{% endif %}</p>    
                        <p><span>Date de la commande :</span>{{ shop.orderDate|date('d/m/Y') }}</p>    
                        <p><span>Date de livraison prévue :</span>{{ shop.shippingDate|date('d/m/Y') }}</p>    
                        <p><span>Montant de la commande :</span>{{ shop.priceOrder }}€</p>        
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}